[package]
name="std"
authors=["David J. Pearce"]
version="0.2.18"

[build]
platforms=["whiley"]

[check]
min=-1
max=1
length=3
depth=1

[build.whiley]
source="src/whiley"
target="bin/wyil"
verify=false
