[package]
name="std"
authors=["David J. Pearce"]
version="0.3.2"

[build]
platforms=["whiley","boogie"]

[build.boogie]
timeout=240

[check]
min=-1
max=1
length=2
depth=1

[build.whiley]
source="src/whiley"
target="bin/wyil"
verify=false
